// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/proto/grpcgwgokit/pb/grpcgwgokit.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *StringMessage) Validate() error {
	return nil
}
